project:
  type: book

book:
  title: "The Algorithm Codex"
  author: "Alejandro Piad-Morffis, Ph.D."
  date: "1/18/2026"
  chapters:
    - index.qmd
    - 00_intro.md
    - part: part1.md
      chapters:
      - 01_search.md
      - 02_binary.md
      - 03_sort.md
      - 04_sort_fast.md
      - 05_rankings.md
      - 06_linear_sort.md
      - lessons_1.md
    - part: part2.md
      chapters: []
    - part: Trees
      chapters: []
    - part: String Matching
      chapters: []
    - part: Graphs
      chapters: []
    - part: Dynamic Programming and Greedy Algorithms
      chapters: []
    - part: Specialized Domains
      chapters: []
    - part: Advanced Complexity
      chapters: []
  appendices:
    - appendix-python.md
    - appendix-notation.md

toc-depth: 2
number-depth: 1

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt