project:
  type: book

book:
  title: "The Algorithm Codex"
  author: "Alejandro Piad-Morffis, Ph.D."
  date: "1/17/2026"
  chapters:
    - index.qmd
    - 01_basic.md

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
